# Generated by Django 5.1.7 on 2025-04-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='level',
            field=models.SmallIntegerField(choices=[(1, '超级'), (2, '普通')], default=2, verbose_name='级别'),
        ),
    ]
