# Generated by Django 5.1.7 on 2025-04-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='userid',
            new_name='username',
        ),
    ]
