# Generated by Django 5.1.7 on 2025-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_rename_userid_order_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('count', models.IntegerField(default=0, verbose_name='人口')),
                ('img', models.FileField(max_length=128, upload_to='city/', verbose_name='Logo')),
            ],
        ),
    ]
